AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://predictionmachine-data/d7244ed57f8a7c9ad45801b2e72c8f08
      Handler: dev.posco.hiona.jobs.AwsFinnhubBars
      Runtime: java8
      Description: Java function
      MemorySize: 1024
      Timeout: 900
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambdaReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - AmazonS3FullAccess
      Tracing: Active
